apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
stringData:
  root-password: {{ .Values.mysql.rootPassword | quote }}
  user: {{ .Values.mysql.user | quote }}
  password: {{ .Values.mysql.password | quote }}
