apiVersion: v2
name: prometheus-stack
description: Prometheus monitoring stack for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: kube-prometheus-stack
    version: "56.0.0"
    repository: https://prometheus-community.github.io/helm-charts
