apiVersion: v2
name: loki-stack
description: Loki log aggregation stack for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: loki-stack
    version: "2.10.2"
    repository: https://grafana.github.io/helm-charts
