apiVersion: v2
name: monitoring-stack
description: A complete monitoring and alerting stack with Prometheus, Grafana, and Alertmanager
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - monitoring
  - prometheus
  - grafana
  - alertmanager
  - metrics
maintainers:
  - name: Platform Team
