{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: alertmanager
    component: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: {{ toJson .Values.alertmanager.config.route.group_by }}
      group_wait: {{ .Values.alertmanager.config.route.group_wait }}
      group_interval: {{ .Values.alertmanager.config.route.group_interval }}
      repeat_interval: {{ .Values.alertmanager.config.route.repeat_interval }}
      receiver: {{ .Values.alertmanager.config.route.receiver | quote }}

    receivers:
      - name: 'slack'
        slack_configs:
          - api_url_file: '/etc/alertmanager/secrets/slack-webhook-url'
            channel: '#alerts'
            title: 'Alert: {{"{{"}}} .GroupLabels.alertname {{"}}"}}'
            text: |
              {{"{{"}}} range .Alerts {{"}}"}}
              *Alert:* {{"{{"}}} .Labels.alertname {{"}}"}}
              *Severity:* {{"{{"}}} .Labels.severity {{"}}"}}
              *Summary:* {{"{{"}}} .Annotations.summary {{"}}"}}
              *Description:* {{"{{"}}} .Annotations.description {{"}}"}}
              {{"{{"}}} end {{"}}"}}
            send_resolved: true
      - name: 'default'
        slack_configs:
          - api_url_file: '/etc/alertmanager/secrets/slack-webhook-url'
            channel: '#alerts'

    {{- if .Values.alertmanager.config.inhibit_rules }}
    inhibit_rules:
      {{- toYaml .Values.alertmanager.config.inhibit_rules | nindent 6 }}
    {{- end }}
{{- end }}
