{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Values.global.namespace }}
  labels:
    app: alertmanager
    component: monitoring
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
  - port: {{ .Values.alertmanager.service.port }}
    targetPort: 9093
    protocol: TCP
    name: http
  selector:
    app: alertmanager
{{- end }}
