{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grafana
    component: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    {{- if .Values.grafana.datasources.prometheus.enabled }}
    - name: Prometheus
      type: prometheus
      access: proxy
      url: {{ .Values.grafana.datasources.prometheus.url }}
      isDefault: {{ .Values.grafana.datasources.prometheus.isDefault }}
      editable: true
    {{- end }}
    {{- if .Values.grafana.datasources.loki.enabled }}
    - name: Loki
      type: loki
      access: proxy
      url: {{ .Values.grafana.datasources.loki.url }}
      isDefault: false
      editable: true
    {{- end }}
{{- end }}
