fluent-bit:
  enabled: true

  # Resource limits
  resources:
    limits:
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 50Mi

  # DaemonSet configuration to run on all nodes
  kind: DaemonSet

  # Service account
  serviceAccount:
    create: true
    name: fluent-bit

  # Configure Fluent Bit to collect logs and send to Loki
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
          Health_Check On

    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*learning-hub*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Kube_URL https://kubernetes.default.svc:443
          Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
          Kube_Tag_Prefix kube.var.log.containers.
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
          Labels On
          Annotations Off

      [FILTER]
          Name nest
          Match kube.*
          Operation lift
          Nested_under kubernetes
          Add_prefix k8s_

      [FILTER]
          Name modify
          Match kube.*
          Remove k8s_pod_id
          Remove k8s_docker_id
          Remove k8s_annotations

      [FILTER]
          Name grep
          Match kube.*
          Regex k8s_namespace_name (dev|prod|staging)

    outputs: |
      [OUTPUT]
          Name loki
          Match kube.*
          Host loki-stack.observability.svc.cluster.local
          Port 3100
          Labels job=fluent-bit, app=$k8s_labels['app'], namespace=$k8s_namespace_name, pod=$k8s_pod_name
          Auto_Kubernetes_Labels On
          Label_keys $k8s_namespace_name,$k8s_pod_name,$k8s_container_name

      [OUTPUT]
          Name loki
          Match host.*
          Host loki-stack.observability.svc.cluster.local
          Port 3100
          Labels job=systemd, host=${HOSTNAME}

    customParsers: |
      [PARSER]
          Name docker_no_time
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L

  # Mount host paths for log collection
  daemonSetVolumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers

  daemonSetVolumeMounts:
    - name: varlog
      mountPath: /var/log
      readOnly: true
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true

  # Tolerations to run on all nodes
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - operator: "Exists"
      effect: "NoExecute"
    - operator: "Exists"
      effect: "NoSchedule"
