fluent-bit:
  # Development environment specific configuration
  config:
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Kube_URL https://kubernetes.default.svc:443
          Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
          Kube_Tag_Prefix kube.var.log.containers.
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
          Labels On
          Annotations Off

      [FILTER]
          Name nest
          Match kube.*
          Operation lift
          Nested_under kubernetes
          Add_prefix k8s_

      [FILTER]
          Name modify
          Match kube.*
          Remove k8s_pod_id
          Remove k8s_docker_id
          Remove k8s_annotations

      [FILTER]
          Name grep
          Match kube.*
          Regex k8s_namespace_name dev
