{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-tls
  labels:
    app: {{ .Chart.Name }}
spec:
  secretName: {{ .Chart.Name }}-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-http
  labels:
    app: {{ .Chart.Name }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: kube-system
      services:
        - name: {{ .Chart.Name }}
          port: {{ .Values.service.port }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-https
  labels:
    app: {{ .Chart.Name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Chart.Name }}
          port: {{ .Values.service.port }}
  tls:
    secretName: {{ .Chart.Name }}-tls-cert
{{- end }}
