loki-stack:
  loki:
    enabled: true
    isDefault: true

    persistence:
      enabled: true
      size: 10Gi
      storageClassName: local-path

    config:
      auth_enabled: false

      ingester:
        chunk_idle_period: 3m
        chunk_block_size: 262144
        chunk_retain_period: 1m
        max_transfer_retries: 0
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1

      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_entries_limit_per_query: 5000
        ingestion_rate_mb: 10
        ingestion_burst_size_mb: 20

      schema_config:
        configs:
          - from: 2024-01-01
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h

      server:
        http_listen_port: 3100
        grpc_listen_port: 9096
        log_level: info

      storage_config:
        boltdb_shipper:
          active_index_directory: /data/loki/boltdb-shipper-active
          cache_location: /data/loki/boltdb-shipper-cache
          cache_ttl: 24h
          shared_store: filesystem
        filesystem:
          directory: /data/loki/chunks

      chunk_store_config:
        max_look_back_period: 0s

      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s

    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

    serviceMonitor:
      enabled: false

    service:
      type: ClusterIP
      port: 3100

  promtail:
    enabled: false  # We're using Fluent Bit instead

  grafana:
    enabled: false  # Grafana should be deployed separately if needed

  prometheus:
    enabled: false  # Prometheus should be deployed separately if needed
