replicaCount: 1

image:
  repository: 541770108352.dkr.ecr.us-east-1.amazonaws.com/learning-hub
  pullPolicy: Always
  tag: "armV0.4"

imagePullSecrets:
  - name: ecr-secret

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: ENVIRONMENT
    value: "development"
  - name: LOG_LEVEL
    value: "debug"

autoscaling:
  enabled: false

ingress:
  enabled: false
